DATABASE_LOCATION = 'data/'
DATABASE_NAME = DATABASE_LOCATION + 'my_db'
BUFFER_ERROR = 50
ERROR = 100
KEY_SIZE = 16
FIELD_SIZE = 8
FIELD_NUM = 7  # ['day', 'month', 'year', 'cases', 'deaths', 'countryterritoryCode', 'popData2018']
RECORD_SIZE = KEY_SIZE + FIELD_NUM * FIELD_SIZE
BUFFER_SIZE = BUFFER_ERROR * RECORD_SIZE
ALL_FIELDS_SIZE = RECORD_SIZE - KEY_SIZE  # size of the all fields except for key